name: "Automatic Blinkers"
overview: "This plugin enables the blinkers for upcoming turns"
description: |
  
  If you have problems, message me on discord.
image_url: ""
version: "1.4.4"
author: "Playzzero97"
